# Problem Statement

This project aims to develop an automated misinformation detection system using BERT, a transformer-based deep learning model. The system analyzes textual data related to health and COVID-19 topics and classifies it as real or fake. By leveraging contextual language understanding, the model helps detect misleading information and contributes to reducing the spread of fake news online.

# Load Dataset

In [4]:
import pandas as pd

# Dataset 1

In [5]:
df1=pd.read_csv(r"C:\Users\farha\Downloads\NLP DL-20260307T180831Z-1-001\NLP DL\covid_val - covid_val.csv")
df1

        id                                              tweet label
0        1  Chinese converting to Islam after realising th...  fake
1        2  11 out of 13 people (from the Diamond Princess...  fake
2        3  COVID-19 Is Caused By A Bacterium, Not Virus A...  fake
3        4  Mike Pence in RNC speech praises Donald Trump’...  fake
4        5  6/10 Sky's @EdConwaySky explains the latest #C...  real
...    ...                                                ...   ...
2135  2136  Donald Trump wrongly claimed that New Zealand ...  fake
2136  2137  Current understanding is #COVID19 spreads most...  real
2137  2138  Nothing screams “I am sat around doing fuck al...  fake
2138  2139  Birx says COVID-19 outbreak not under control ...  fake
2139  2140  Another 4422 new coronavirus cases have been c...  real

[2140 rows x 3 columns]

# Basic Understanding (EDA)

In [6]:
df1.isnull().sum()

id       0
tweet    0
label    0
dtype: int64

In [7]:
df1.duplicated().sum()

np.int64(0)

In [8]:
df1["label"].value_counts()

label
real    1120
fake    1020
Name: count, dtype: int64

In [9]:
df1 = df1[['tweet','label']]
df1 = df1.rename(columns={'tweet':'text'})

df1['label'] = df1['label'].replace({
    'fake': 'fake',
    'real': 'real'
})

# Merging

# Dataset 2

In [10]:
df2=pd.read_csv(r"C:\Users\farha\Downloads\NLP DL-20260307T180831Z-1-001\NLP DL\fakehealth_cleaned - fakehealth_cleaned.csv")
df2

,statement,label,source
0,Virtual reality to help detect early risk of A...,Misleading,FakeHealth
1,Evofem's birth control gel meets main study go...,Partially True,FakeHealth
2,How a breakthrough new fertility test is offer...,Partially True,FakeHealth
3,J&J says its psoriasis drug superior to Novart...,Partially True,FakeHealth
4,Incontinence Drug May Cut Hot Flashes in Breas...,TRUE,FakeHealth
...,...,...,...
2291,The Baseball Diet Is Proving To Be A Heavy Fav...,Misleading,FakeHealth
2292,Stem Cell Injection May Soon Reverse Vision Lo...,Partially True,FakeHealth
2293,Overnight Fasting May Reduce Breast Cancer Ris...,Partially True,FakeHealth
2294,Joslin Researchers Conduct First Trial Directl...,TRUE,FakeHealth
2295,Prostate Cancer Drug Slows Memory Loss in Wome...,Partially True,FakeHealth

In [11]:
df2["label"].value_counts()

label
Partially True    1289
TRUE               784
Misleading         190
FALSE               33
Name: count, dtype: int64

In [12]:
df2.isnull().sum()

statement    0
label        0
source       0
dtype: int64

In [13]:
df2.duplicated().sum()

np.int64(0)

In [14]:
print(df2['label'].unique())

['Misleading' 'Partially True' 'TRUE' 'FALSE']

In [15]:
df2 = df2[['statement','label']]
df2 = df2.rename(columns={'statement':'text'})

df2['label'] = df2['label'].replace({
    'TRUE':'real',
    'True':'real',
    'Partially True':'real',
    'Misleading':'fake',
    'FALSE':'fake'
})

# Dataset 3

In [16]:
df3 = pd.read_csv("FakeCovid_July2020.csv")

In [17]:
df3.head()

,ID,ref_category_title,ref_url,pageid,verifiedby,country,class,title,published_date,country1,country2,country3,country4,article_source,ref_source,source_title,content_text,category,lang
0,FC1,FALSE: The coronavirus is an amplified bacteri...,https://www.poynter.org/?ifcn_misinformation=t...,https://www.poynter.org/ifcn-covid-19-misinfor...,La Silla Vacía,Colombia,FALSE,The coronavirus is an amplified bacteria rela...,2020/06/17,Colombia,NaN,NaN,NaN,https://lasillavacia.com/detector-video-falso-...,poynter,Detector a video falso que dice que el Covid e...,La Silla Vacía usa Cookies para mejorar la exp...,NaN,es
1,FC2,FALSE: A law allows people to go for a run dur...,https://www.poynter.org/?ifcn_misinformation=a...,https://www.poynter.org/ifcn-covid-19-misinfor...,Newtral.es,Spain,FALSE,A law allows people to go for a run during th...,2020/04/09,Spain,NaN,NaN,NaN,https://www.newtral.es/la-broma-de-que-a-los-r...,poynter,La broma de que a los “runners” se les permite...,En los últimos días nos ha llegado una consult...,NaN,es
2,FC3,False: Chinese converting to Islam after reali...,https://www.poynter.org/?ifcn_misinformation=c...,https://www.poynter.org/ifcn-covid-19-misinfor...,FactCrescendo,India,False,Chinese converting to Islam after realizing t...,2020/02/20,India,NaN,NaN,NaN,https://english.factcrescendo.com/2020/02/20/c...,poynter,Are Chinese people converting to Islam in fear...,"The fact behind every news!, Ever since the Wo...",NaN,en
3,FC4,False: Bat market and bat meat are being sold ...,https://www.poynter.org/?ifcn_misinformation=b...,https://www.poynter.org/ifcn-covid-19-misinfor...,France 24 Observers,France,False,Bat market and bat meat are being sold in Wuhan.,2020/01/27,France,NaN,NaN,NaN,https://observers.france24.com/fr/20200130-int...,poynter,"La soupe à la chauve-souris, un plat prisé en ...","عربي, English, Français, Contribuer, فارسی, عر...",NaN,fr
4,FC5,False: You can self-diagnose COVID-19 by holdi...,https://www.poynter.org/?ifcn_misinformation=y...,https://www.poynter.org/ifcn-covid-19-misinfor...,Agência Lupa,Brazil,False,You can self-diagnose COVID-19 by holding you...,2020/03/16,Brazil,NaN,NaN,NaN,https://piaui.folha.uol.com.br/lupa/2020/03/16...,poynter,#Verificamos: É falso que quem consegue prende...,", “O novo CORONA VÍRUS pode não mostrar sinais...",NaN,pt

In [18]:
df3 = df3.rename(columns={
    'content_text': 'text',
    'class': 'label'
})

In [19]:
df3 = df3[['text','label']]

In [20]:
df3.isnull().sum()

text     778
label      2
dtype: int64

# remove null values

In [21]:
df3 = df3.dropna(subset=['text','label'])

In [22]:
df3.isnull().sum()

text     0
label    0
dtype: int64

# remove duplicates

In [23]:
df3.duplicated().sum()

np.int64(220)

In [24]:
df3.drop_duplicates(inplace=True)

In [25]:
df3["label"].value_counts()

label
FALSE                          2794
False                          2659
Misleading                      339
MISLEADING                      159
Mostly false                     99
Partly false                     94
misleading                       78
No evidence                      52
Mostly False                     43
Explanatory                      40
Mixture                          34
True                             31
No Evidence                      21
News                             20
PARTLY FALSE                     11
Unproven                         11
MOSTLY FALSE                     11
Partly False                     10
Correct Attribution              10
mostly false                      9
partly false                      9
Mostly True                       8
Miscaptioned                      8
Misattributed                     7
MOSTLY TRUE                       7
HALF TRUE                         6
Partially false                   5
(Org. doesn't apply rating)       4
Labeled Satire                    4
Fake                              4
no evidence                       3
Half True                         3
false                             3
half true                         2
Scam                              2
NO EVIDENCE                       2
Partly FALSE                      2
PARTLY TRUE                       2
mislEADING                        2
Correct                           2
false and misleading              1
Not true                          1
Partly true                       1
Two Pinocchios                    1
PANTS ON FIRE                     1
IN DISPUTE                        1
MiSLEADING                        1
Partially correct                 1
Unlikely                          1
True but                          1
Mostly true                       1
Collections                       1
Mixed                             1
Unverified                        1
Partially true                    1
Name: count, dtype: int64

In [26]:
df3['label'] = df3['label'].str.lower().str.strip()

In [27]:
real_labels = [
    'true','mostly true','correct attribution','explanatory','news','partially true'
]

df3['label'] = df3['label'].apply(lambda x: 'real' if x in real_labels else 'fake')

In [28]:
df3['label'].value_counts()

label
fake    6507
real     118
Name: count, dtype: int64

# Merge all dataset

In [29]:
final_df = pd.concat([df1, df2, df3], ignore_index=True)

print(final_df['label'].value_counts())

label
fake    7750
real    3311
Name: count, dtype: int64

# Encoding

# Label Encoding

In [30]:
label_map = {'fake':0, 'real':1}

final_df['label'] = final_df['label'].map(label_map)  
print(final_df['label'].isnull().sum())

0

In [31]:
final_df['label'].value_counts()

label
0    7750
1    3311
Name: count, dtype: int64

# Normalization Function

In [32]:
import re

def clean_text(text):
    
    # convert to lowercase
    text = text.lower()
    
    # remove URLs
    text = re.sub(r'http\S+|www\S+', '', text)
    
    # remove HTML tags 
    text = re.sub(r'<.*?>', '', text)
    
    # remove special characters except letters and numbers
    text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
    
    # remove extra spaces
    text = re.sub(r'\s+', ' ', text).strip()
    
    return text

In [33]:
final_df['text'] = final_df['text'].apply(clean_text)

#  Remove Empty Text After Cleaning

In [34]:
final_df = final_df[final_df['text'].str.strip() != ""]

In [35]:
final_df.duplicated().sum()

np.int64(146)

In [36]:
final_df = final_df.drop_duplicates()

In [37]:
final_df.shape

(10909, 2)

# Train/Test Split

In [38]:
from sklearn.model_selection import train_test_split

X = final_df['text']
y = final_df['label']

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [39]:
final_df["label"].value_counts()

label
0    7605
1    3304
Name: count, dtype: int64

# balancing the train process using class weight

In [40]:
from sklearn.utils.class_weight import compute_class_weight
import numpy as np

classes = np.unique(y_train)
weights = compute_class_weight(
    class_weight='balanced',
    classes=classes,
    y=y_train
)

class_weights = dict(zip(classes, weights))

print(class_weights)

{np.int64(0): np.float64(0.7172090729783037), np.int64(1): np.float64(1.6509648127128262)}

# DistilBERT

In [41]:
!pip install transformers

Requirement already satisfied: transformers in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (5.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (1.3.3)
Requirement already satisfied: numpy>=1.17 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (2.3.4)
Requirement already satisfied: packaging>=20.0 in c:\users\farha\appdata\roaming\python\python312\site-packages (from transformers) (25.0)
Requirement already satisfied: pyyaml>=5.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (2026.1.15)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: tqdm>=4.27 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (4.67.1)
Requirement already satisfied: filelock in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2026.1.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: typer-slim in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.21.1)
Requirement already satisfied: typing-extensions>=4.1.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (4.15.0)
Requirement already satisfied: anyio in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: certifi in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (2025.11.12)
Requirement already satisfied: httpcore==1.* in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: idna in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (3.11)
Requirement already satisfied: h11>=0.16 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: colorama in c:\users\farha\appdata\roaming\python\python312\site-packages (from tqdm>=4.27->transformers) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from typer->transformers) (8.3.1)
Requirement already satisfied: rich>=10.11.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from typer->transformers) (14.3.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from rich>=10.11.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\farha\appdata\roaming\python\python312\site-packages (from rich>=10.11.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers) (0.1.2)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [42]:
from transformers import DistilBertTokenizer

tokenizer = DistilBertTokenizer.from_pretrained("distilbert-base-uncased")

In [43]:
train_encodings = tokenizer(
    X_train.tolist(),
    truncation=True,
    padding="max_length",
    max_length=128
)

test_encodings = tokenizer(
    X_test.tolist(),
    truncation=True,
    padding="max_length",
    max_length=128
)

# create dataset class

In [44]:
!pip install torch

Requirement already satisfied: torch in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (2.10.0+cpu)
Requirement already satisfied: filelock in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from torch) (2026.1.0)
Requirement already satisfied: setuptools in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from torch) (80.10.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch) (3.0.3)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [45]:
import torch
from torch.utils.data import Dataset, DataLoader

In [46]:
class FakeNewsDataset(Dataset):

    def __init__(self, encodings, labels):
        self.encodings = encodings
        self.labels = labels

    def __getitem__(self, idx):
        item = {key: torch.tensor(val[idx]) for key, val in self.encodings.items()}
        item["labels"] = torch.tensor(self.labels.iloc[idx])
        return item

    def __len__(self):
        return len(self.labels)

# create train and test dataset

In [47]:
train_dataset = FakeNewsDataset(train_encodings, y_train)
test_dataset = FakeNewsDataset(test_encodings, y_test)

In [48]:
print(len(train_dataset))
print(len(test_dataset))

8727
2182

# DataLoader

In [51]:


train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=16)

In [52]:
for batch in train_loader:
    print(batch.keys())
    break

dict_keys(['input_ids', 'attention_mask', 'labels'])

# load the model

In [53]:
from transformers import DistilBertForSequenceClassification

model = DistilBertForSequenceClassification.from_pretrained(
    "distilbert-base-uncased",
    num_labels=2
)

Loading weights: 100%|██████████| 100/100 [00:00<00:00, 2610.36it/s]
DistilBertForSequenceClassification LOAD REPORT from: distilbert-base-uncased
Key                     | Status     |
------------------------+------------+-
vocab_transform.bias    | UNEXPECTED |
vocab_projector.bias    | UNEXPECTED |
vocab_layer_norm.weight | UNEXPECTED |
vocab_layer_norm.bias   | UNEXPECTED |
vocab_transform.weight  | UNEXPECTED |
classifier.bias         | MISSING    |
pre_classifier.bias     | MISSING    |
pre_classifier.weight   | MISSING    |
classifier.weight       | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

# move model to device

In [54]:
import torch

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

If GPU is available, training will be much faster.

# Define Optimizer

In [55]:
from torch.optim import AdamW

optimizer = AdamW(model.parameters(), lr=5e-5)

# Training Loop

In [56]:
from tqdm import tqdm

model.train()

for epoch in range(3):

    for batch in tqdm(train_loader):

        optimizer.zero_grad()

        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels
        )

        loss = outputs.loss

        loss.backward()

        optimizer.step()

    print("Epoch completed")

100%|██████████| 546/546 [51:39<00:00,  5.68s/it]

Epoch completed

100%|██████████| 546/546 [2:43:17<00:00, 17.94s/it]

Epoch completed

100%|██████████| 546/546 [58:35<00:00,  6.44s/it]

Epoch completed

# Evaluate model

In [57]:
model.eval()

correct = 0
total = 0

with torch.no_grad():

    for batch in test_loader:

        input_ids = batch["input_ids"].to(device)
        attention_mask = batch["attention_mask"].to(device)
        labels = batch["labels"].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)

        preds = torch.argmax(outputs.logits, dim=1)

        correct += (preds == labels).sum().item()
        total += labels.size(0)

accuracy = correct / total
print("Test Accuracy:", accuracy)

Test Accuracy: 0.9518790100824931

# Save Model

In [ ]:
model.save_pretrained("bert_misinformation_model")
tokenizer.save_pretrained("bert_misinformation_model")

('bert_misinformation_model\\tokenizer_config.json',
 'bert_misinformation_model\\special_tokens_map.json',
 'bert_misinformation_model\\vocab.txt',
 'bert_misinformation_model\\added_tokens.json')

# Prediction Function

In [58]:
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer
import torch

model = DistilBertForSequenceClassification.from_pretrained("bert_misinformation_model")
tokenizer = DistilBertTokenizer.from_pretrained("bert_misinformation_model")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

model.eval()

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 3007.60it/s]

DistilBertForSequenceClassification(
  (distilbert): DistilBertModel(
    (embeddings): Embeddings(
      (word_embeddings): Embedding(30522, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (transformer): Transformer(
      (layer): ModuleList(
        (0-5): 6 x TransformerBlock(
          (attention): DistilBertSelfAttention(
            (q_lin): Linear(in_features=768, out_features=768, bias=True)
            (k_lin): Linear(in_features=768, out_features=768, bias=True)
            (v_lin): Linear(in_features=768, out_features=768, bias=True)
            (out_lin): Linear(in_features=768, out_features=768, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (sa_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
          (ffn): FFN(
            (dropout): Dropout(p=0.1, inplace=False)
            (lin1): Linear(in_features=768, out_features=3072, bias=True)
            (lin2): Linear(in_features=3072, out_features=768, bias=True)
            (activation): GELUActivation()
          )
          (output_layer_norm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
        )
      )
    )
  )
  (pre_classifier): Linear(in_features=768, out_features=768, bias=True)
  (classifier): Linear(in_features=768, out_features=2, bias=True)
  (dropout): Dropout(p=0.2, inplace=False)
)

In [59]:
def predict(text):

    inputs = tokenizer(
        text,
        return_tensors="pt",
        truncation=True,
        padding=True,
        max_length=512
    )

    input_ids = inputs["input_ids"].to(device)
    attention_mask = inputs["attention_mask"].to(device)

    with torch.no_grad():

        outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask
        )

    logits = outputs.logits
    prediction = torch.argmax(logits, dim=1).item()

    return prediction

 # test the model

In [62]:
text = "Vaccines cause autism"

result = predict(text)

print(result)

0

In [66]:
labels = ["Fake", "Real"]

In [67]:
print("Prediction:", labels[result])

Prediction: Fake

# Streamlit App

In [69]:
pip install streamlit lime transformers torch

Requirement already satisfied: streamlit in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (1.51.0)
Collecting lime
  Downloading lime-0.2.0.1.tar.gz (275 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: transformers in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (5.3.0)
Requirement already satisfied: torch in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (2.10.0+cpu)
Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.5.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<7,>=4.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (6.2.2)
Requirement already satisfied: click<9,>=7.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (8.3.1)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (2.3.4)
Requirement already satisfied: packaging<26,>=20 in c:\users\farha\appdata\roaming\python\python312\site-packages (from streamlit) (25.0)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (2.3.3)
Requirement already satisfied: pillow<13,>=7.1.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (12.0.0)
Requirement already satisfied: protobuf<7,>=3.20 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (6.33.1)
Requirement already satisfied: pyarrow<22,>=7.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (21.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (2.32.5)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (9.1.2)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.4.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (4.15.0)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (3.1.45)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (0.9.1)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\farha\appdata\roaming\python\python312\site-packages (from streamlit) (6.5.2)
Requirement already satisfied: jinja2 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)
Requirement already satisfied: jsonschema>=3.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.1)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.12.0)
Requirement already satisfied: colorama in c:\users\farha\appdata\roaming\python\python312\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\farha\appdata\roaming\python\python312\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.11.12)
Requirement already satisfied: matplotlib in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from lime) (3.10.7)
Requirement already satisfied: scipy in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from lime) (1.16.3)
Requirement already satisfied: tqdm in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from lime) (4.67.1)
Requirement already satisfied: scikit-learn>=0.18 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from lime) (1.8.0)
Collecting scikit-image>=0.12 (from lime)
  Downloading scikit_image-0.26.0-cp312-cp312-win_amd64.whl.metadata (15 kB)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (1.3.3)
Requirement already satisfied: pyyaml>=5.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (2026.1.15)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.22.2)
Requirement already satisfied: typer in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from transformers) (0.7.0)
Requirement already satisfied: filelock in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (3.20.3)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (2026.1.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.28.1)
Requirement already satisfied: shellingham in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (1.5.4)
Requirement already satisfied: typer-slim in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub<2.0,>=1.3.0->transformers) (0.21.1)
Requirement already satisfied: anyio in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (4.12.1)
Requirement already satisfied: httpcore==1.* in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (1.0.9)
Requirement already satisfied: h11>=0.16 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers) (0.16.0)
Requirement already satisfied: sympy>=1.13.3 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: setuptools in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from torch) (80.10.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.29.0)
Requirement already satisfied: six>=1.5 in c:\users\farha\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Collecting imageio!=2.35.0,>=2.33 (from scikit-image>=0.12->lime)
  Downloading imageio-2.37.3-py3-none-any.whl.metadata (9.7 kB)
Collecting tifffile>=2022.8.12 (from scikit-image>=0.12->lime)
  Downloading tifffile-2026.3.3-py3-none-any.whl.metadata (31 kB)
Collecting lazy-loader>=0.4 (from scikit-image>=0.12->lime)
  Downloading lazy_loader-0.5-py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: joblib>=1.3.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn>=0.18->lime) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from scikit-learn>=0.18->lime) (3.6.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->lime) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->lime) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->lime) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->lime) (1.4.9)
Requirement already satisfied: pyparsing>=3 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from matplotlib->lime) (3.2.5)
Requirement already satisfied: rich>=10.11.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from typer->transformers) (14.3.1)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from rich>=10.11.0->typer->transformers) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\farha\appdata\roaming\python\python312\site-packages (from rich>=10.11.0->typer->transformers) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in c:\users\farha\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich>=10.11.0->typer->transformers) (0.1.2)
Downloading scikit_image-0.26.0-cp312-cp312-win_amd64.whl (11.9 MB)
   ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/11.9 MB 2.8 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/11.9 MB 2.8 MB/s eta 0:00:04
   ----- ---------------------------------- 1.6/11.9 MB 2.6 MB/s eta 0:00:04
   ------- -------------------------------- 2.1/11.9 MB 2.6 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/11.9 MB 2.6 MB/s eta 0:00:04
   ---------- ----------------------------- 3.1/11.9 MB 2.6 MB/s eta 0:00:04
   ------------ --------------------------- 3.7/11.9 MB 2.5 MB/s eta 0:00:04
   -------------- ------------------------- 4.2/11.9 MB 2.5 MB/s eta 0:00:04
   --------------- ------------------------ 4.7/11.9 MB 2.5 MB/s eta 0:00:03
   ----------------- ---------------------- 5.2/11.9 MB 2.6 MB/s eta 0:00:03
   ------------------- -------------------- 5.8/11.9 MB 2.6 MB/s eta 0:00:03
   ---------------------- ----------------- 6.6/11.9 MB 2.5 MB/s eta 0:00:03
   ----------------------- ---------------- 7.1/11.9 MB 2.6 MB/s eta 0:00:02
   ------------------------- -------------- 7.6/11.9 MB 2.6 MB/s eta 0:00:02
   --------------------------- ------------ 8.1/11.9 MB 2.6 MB/s eta 0:00:02
   ----------------------------- ---------- 8.7/11.9 MB 2.6 MB/s eta 0:00:02
   ------------------------------ --------- 9.2/11.9 MB 2.5 MB/s eta 0:00:02
   -------------------------------- ------- 9.7/11.9 MB 2.5 MB/s eta 0:00:01
   ---------------------------------- ----- 10.2/11.9 MB 2.5 MB/s eta 0:00:01
   ------------------------------------ --- 10.7/11.9 MB 2.5 MB/s eta 0:00:01
   ------------------------------------- -- 11.3/11.9 MB 2.5 MB/s eta 0:00:01
   -------------------------------------- - 11.5/11.9 MB 2.5 MB/s eta 0:00:01
   ---------------------------------------- 11.9/11.9 MB 2.5 MB/s  0:00:04
Downloading imageio-2.37.3-py3-none-any.whl (317 kB)
Downloading lazy_loader-0.5-py3-none-any.whl (8.0 kB)
Downloading tifffile-2026.3.3-py3-none-any.whl (243 kB)
Building wheels for collected packages: lime
  Building wheel for lime (pyproject.toml): started
  Building wheel for lime (pyproject.toml): finished with status 'done'
  Created wheel for lime: filename=lime-0.2.0.1-py3-none-any.whl size=283917 sha256=589722c49b996757cfeb8ad288193518e97e1971b122c294990171160163a0a9
  Stored in directory: c:\users\farha\appdata\local\pip\cache\wheels\e7\5d\0e\4b4fff9a47468fed5633211fb3b76d1db43fe806a17fb7486a
Successfully built lime
Installing collected packages: tifffile, lazy-loader, imageio, scikit-image, lime

   ---------------------------------------- 0/5 [tifffile]
   ---------------- ----------------------- 2/5 [imageio]
   ------------------------ --------------- 3/5 [scikit-image]
   ------------------------ --------------- 3/5 [scikit-image]
   ------------------------ --------------- 3/5 [scikit-image]
   ------------------------ --------------- 3/5 [scikit-image]
   ---------------------------------------- 5/5 [lime]

Successfully installed imageio-2.37.3 lazy-loader-0.5 lime-0.2.0.1 scikit-image-0.26.0 tifffile-2026.3.3
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
pip install streamlit

Requirement already satisfied: streamlit in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (1.41.1)
Requirement already satisfied: altair<6,>=4.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (5.5.0)
Requirement already satisfied: blinker<2,>=1.0.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (1.9.0)
Requirement already satisfied: cachetools<6,>=4.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (8.3.1)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (1.26.4)
Requirement already satisfied: packaging<25,>=20 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (24.1)
Requirement already satisfied: pandas<3,>=1.4.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (2.2.3)
Requirement already satisfied: pillow<12,>=7.1.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (11.0.0)
Requirement already satisfied: protobuf<6,>=3.20 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (5.29.3)
Requirement already satisfied: pyarrow>=7.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (19.0.0)
Requirement already satisfied: requests<3,>=2.27 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (2.32.3)
Requirement already satisfied: rich<14,>=10.14.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (13.9.4)
Requirement already satisfied: tenacity<10,>=8.1.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (9.0.0)
Requirement already satisfied: toml<2,>=0.10.1 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (0.10.2)
Requirement already satisfied: typing-extensions<5,>=4.3.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (4.12.2)
Requirement already satisfied: watchdog<7,>=2.1.5 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (6.0.0)
Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (3.1.44)
Requirement already satisfied: pydeck<1,>=0.8.0b4 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from streamlit) (0.9.1)
Requirement already satisfied: tornado<7,>=6.0.3 in c:\users\pc\appdata\roaming\python\python312\site-packages (from streamlit) (6.4.2)
Requirement already satisfied: jinja2 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from altair<6,>=4.0->streamlit) (3.1.5)
Requirement already satisfied: jsonschema>=3.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from altair<6,>=4.0->streamlit) (4.23.0)
Requirement already satisfied: narwhals>=1.14.2 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from altair<6,>=4.0->streamlit) (1.24.1)
Requirement already satisfied: colorama in c:\users\pc\appdata\roaming\python\python312\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2024.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from requests<3,>=2.27->streamlit) (2025.1.31)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from rich<14,>=10.14.0->streamlit) (3.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\pc\appdata\roaming\python\python312\site-packages (from rich<14,>=10.14.0->streamlit) (2.18.0)
Requirement already satisfied: smmap<6,>=3.0.1 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from jinja2->altair<6,>=4.0->streamlit) (2.1.5)
Requirement already satisfied: attrs>=22.2.0 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (25.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.36.2)
Requirement already satisfied: rpds-py>=0.7.1 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from jsonschema>=3.0->altair<6,>=4.0->streamlit) (0.22.3)
Requirement already satisfied: mdurl~=0.1 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from markdown-it-py>=2.2.0->rich<14,>=10.14.0->streamlit) (0.1.2)
Requirement already satisfied: six>=1.5 in c:\users\pc\appdata\local\programs\python\python312\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [70]:
import streamlit as st
import torch
import torch.nn.functional as F
from transformers import DistilBertForSequenceClassification, DistilBertTokenizer
from lime.lime_text import LimeTextExplainer

# Load model
model = DistilBertForSequenceClassification.from_pretrained("bert_misinformation_model")
tokenizer = DistilBertTokenizer.from_pretrained("bert_misinformation_model")

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)
model.eval()

labels = ["Fake", "Real"]

# Prediction function
def predict_proba(texts):

    inputs = tokenizer(
        texts,
        return_tensors="pt",
        padding=True,
        truncation=True,
        max_length=512
    )

    input_ids = inputs["input_ids"].to(device)
    attention_mask = inputs["attention_mask"].to(device)

    with torch.no_grad():
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)

    probs = F.softmax(outputs.logits, dim=1)

    return probs.cpu().numpy()


# Streamlit UI
st.title("Medical Misinformation Detection")

st.write("Enter a medical statement to check if it is misinformation.")

text = st.text_area("Enter Text")

if st.button("Predict"):

    if text:

        probs = predict_proba([text])[0]
        prediction = probs.argmax()

        confidence = probs[prediction]

        st.subheader("Prediction")
        st.write(labels[prediction])

        st.subheader("Confidence")
        st.write(f"{confidence*100:.2f}%")

        # Explainable AI using LIME
        st.subheader("Explanation")

        explainer = LimeTextExplainer(class_names=labels)

        exp = explainer.explain_instance(
            text,
            predict_proba,
            num_features=10
        )

        html = exp.as_html()
        st.components.v1.html(html, height=400, scrolling=True)

Loading weights: 100%|██████████| 104/104 [00:00<00:00, 12034.64it/s]
2026-03-09 23:22:19.814 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.006
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run C:\Users\farha\AppData\Roaming\Python\Python312\site-packages\ipykernel_launcher.py [ARGUMENTS]
2026-03-09 23:22:20.008 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.008 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.008 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.008 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.008 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.011 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.011 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.011 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.012 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.012 Session state does not function when running a script without `streamlit run`
2026-03-09 23:22:20.013 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.013 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.013 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.016 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.016 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.017 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.017 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.017 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.
2026-03-09 23:22:20.018 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.